bulma_classes = {
    'main': 'container',
    'h1': 'title',
    'h2': 'title',
    'h3': 'title',
    'p': 'content',
    'div.body': 'container',
    'a': 'is-link',
    'button': 'button is-link',
    'ul': 'list is-hoverable',
    'ol': 'list is-hoverable',
    'li': 'list-item',
    'dl': 'list',
    'dt': 'list-item-title',
    'dd': 'list-item',
    'note': 'notification is-primary',
    'figure': 'image',
    'image' : 'is-rounded is-bordered',
    'div.note' : 'notification is-info',
    'gallery' : 'columns is-multiline is-variable is-8',
    'section': 'content',
}

