name: Build HTML

on:
  workflow_dispatch:
  workflow_call: 

jobs:
  build-html:
    name: Build HTML 5 using the latest DITA Open Toolkit
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the dita branch
        uses: actions/checkout@v4
        with:
          ref: dita

      - name: Delete out folder
        run: |
          echo "Deleting out folder"
          rm -rf out
        
      - name: Create out folder
        run: |
          echo "Creating out folder"
          mkdir -p $(pwd)/out
          ls -la
          
      - name: Build HTML5
        #uses: dita-ot/dita-ot-action@master workaround to  https://github.com/dita-ot/dita-ot-action/issues/11
        uses: dita-ot/dita-ot-action@4.3
        with:
          build: |
            set -e
            dita --version
            echo " dita --input=$(pwd)/content/en/orange-heart-master.ditamap --format=html5 --verbose --output=$(pwd)/out  --propertyfile=$(pwd)/resources/build.properties -Dargs.input.dir=$(pwd) "
            dita --input=$(pwd)/content/en/orange-heart-master.ditamap --format=html5 --verbose  --output=$(pwd)/out --propertyfile=$(pwd)/resources/build.properties -Dargs.input.dir=$(pwd) 2>&1 | tee log.txt
            ls -R 
            
      - name: Upload log file as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-log-html5-txt
          path: log.txt

      - name: Upload DITA Output to a ZIP file
        uses: actions/upload-artifact@v4
        with:
          name: out-html5-archive 
          path: 'out'
  
      - name: List build output and errors
        run: |
          if grep -qEi 'Error|ERROR' log.txt; then
              echo "Errors detected in DITA OT build log:"
              grep -Ei 'Error|ERROR' log.txt
              exit 1
          fi
          ls -R out

      - name: Delete out folder
        run: |
          #echo "Deleting out folder"
          #sudo chown -R $USER:$USER out
          #rm -rf out

      - name: Configure git
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"

      
      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          if git diff-index --quiet HEAD; then
            echo "No changes to commit"
          else
            git add .
            git commit -m "Github workflow ran DITA OT and generated html5 to out folder"
            git push https://${{secrets.GH_TOKEN}}@github.com/yetessam/orange-heart-image-addressing.git dita
          fi
      - name: Summarize build
        run: |
          echo "### Summary " >> $GITHUB_STEP_SUMMARY
          echo "$(cat log.txt)" >> $GITHUB_STEP_SUMMARY
