name: Algolia Recrawl
on:
  push:
    branches: [ prod ]
 
  jobs:
  algolia_crawl:
    name: Algolia Recrawl
    runs-on: ubuntu-latest
    steps:
      
      # We don't know when the site will be deployed. To do: Consider writing a loop to query the deployment
      # status using curl to return the deployment status from  Fleek API, for now we just wait a few seconds
      
      #name: Sleep for 30s
      #  run: sleep 30
      
      name: Algolia crawler creation and crawl
      uses: algolia/algoliasearch-crawler-github-actions@v1.0.10
      id: algolia_crawler
      with: # mandatory parameters
          crawler-user-id: ${{ secrets.CRAWLER_USER_ID }}
          crawler-api-key: ${{ secrets.CRAWLER_API_KEY }}
          algolia-app-id: ${{ secrets.ALGOLIA_APP_ID }}
          algolia-api-key: ${{ secrets.ALGOLIA_API_KEY }}
          site-url: 'https://example.com'
