name: Algolia Recrawl

on:
  workflow_dispatch:
  push:
    branches:
      - prod

jobs:
  algolia_crawl:
    name: Algolia Recrawl
    runs-on: ubuntu-latest
    environment: default  # Specify the environment here

    steps:
      # Optional: Wait for deployment status (commented out for now)
      # name: Sleep for 30 seconds to ensure the site is deployed
      # run: sleep 30

      # Step: Start the Algolia crawler
      - name: Algolia crawler creation and crawl
        uses: algolia/algoliasearch-crawler-github-actions@v1.0.10
        id: algolia_crawler
        with:
          # Mandatory parameters
          crawler-user-id: ${{ secrets.CRAWLER_USER_ID }}
          crawler-api-key: ${{ secrets.CRAWLER_API_KEY }}
          algolia-app-id: ${{ secrets.ALGOLIA_APP_ID }}
          algolia-api-key: ${{ secrets.ALGOLIA_API_KEY }}
          site-url: ${{ secrets.SITE_URL }}  # URL stored in the environment secrets
