name: Deploy XML to XML Branch

on:
  workflow_dispatch:  # This will allow manual dispatch of the workflow
  workflow_call: 
 # push:
 #   branches: [ stage ]

jobs:
  deploy-xml-to-xml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout DITA Branch
        uses: actions/checkout@v3
        with:
          ref: dita

      - name: Copy DITA Folder to Temporary Location
        run: cp -r content /tmp/content

      - name: Checkout or Create XML Branch
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

          
          git fetch origin
          if git show-ref --quiet refs/remotes/origin/xml; then
            # If the branch exists, check it out and reset it to match the remote
            git checkout xml
            git reset --hard origin/xml
          else
            # If the branch doesn't exist, create it as an orphan branch
            git checkout -b xml
            git commit --allow-empty -m "Initial commit for XML branch"
            git push origin xml
          fi

      - name: Remove Existing xml Folder
        run: rm -rf src/xml

      - name: Create src Directory (if it doesn't exist)
        run: mkdir -p src

      - name: Move src Folder from Temporary Location
        run: mv /tmp/content ./src/xml

      - name: Commit and Push Changes
        run: |
          git add src/xml
          git commit -m 'Deployed XML content folder from dita branch to xml branch'  
          git push origin xml --force  # Force push to overwrite remote branch
