name: Build DITA files
'on':
  push:
    branches:
      - dita

jobs:
  build-dita:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Delete out folder
        run: |
          echo "Deleting out folder"
          rm -rf out

      - name: Build HTML5 
        uses: dita-ot/dita-ot-action@master
        with:
          build: |
            dita --input=dita/orange-heart.ditamap --format=html5 --verbose  --propertyfile=dita/html5.properties 2>&1 | tee log.txt

      - name: Upload log file as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: DITA OT log
          path: log.txt

      - name: Modify HTML head while preserving the title
        run: |
          for file in out/*.html; do
            # Extract the title tag
            title=$(sed -n 's/.*<title>\(.*\)<\/title>.*/\1/p' "$file")

            # Replace the head section
            sed -i "/<head>/,/<\/head>/c\<head>\n    <meta charset=\"UTF-8\">\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n    <title>$title<\/title>\n    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/bulma/0.9.3/css/bulma.min.css\">\n<\/head>" "$file"
          done


      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Build Output 
          path: 'out' # The folder the action should upload.
          
      - name: List build output
        run: ls -R out

      - name: Configure git
        run: |
          git config --global user.email "yasisay@gmail.com"
          git config --global user.name "Yas Etessam"

      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git add out
          if git diff-index --quiet HEAD; then
            echo "No changes to commit"
          else
            git commit -m "Build DITA files"
            git push https://${{ secrets.GH_TOKEN }}@github.com/yetessam/orange-heart-image-addressing.git dita
          fi

      - name: Summarize build
        run: |
          echo "### Summary " >> $GITHUB_STEP_SUMMARY
          echo "$(cat log.txt)" >> $GITHUB_STEP_SUMMARY
