name: DITA Workflow

on:
  push:
    branches:
      - dita

jobs:
  build-html:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the dita branch
        uses: actions/checkout@v2
        with:
          ref: dita

      - name: Delete out folder
        run: |
          echo "Deleting out folder"
          rm -rf out

      - name: Build HTML5
        uses: dita-ot/dita-ot-action@master
        with:
          build: |
            set -e
            dita --input=dita/orange-heart.ditamap --format=html5 --verbose --propertyfile=dita/html5.properties 2>&1 | tee log.txt

      - name: Upload log file as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: DITA OT log
          path: log.txt

      - name: Archive the 'out' folder
        run: |
          set -e
          tar -czf out.tar.gz out

      - name: Upload 'out' folder archive
        uses: actions/upload-artifact@v4
        with:
          name: out-html5-archive
          path: out.tar.gz
    
      - name: List build output
        run: ls -R out

      - name: Configure git
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"

      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git add out
          if git diff-index --quiet HEAD; then
            echo "No changes to commit"
          else
            git commit -m "Build DITA to html5 "
            git push https://${{ secrets.GH_TOKEN }}@github.com/yetessam/orange-heart-image-addressing.git dita
          fi

      - name: Summarize build
        run: |
          echo "### Summary " >> $GITHUB_STEP_SUMMARY
          echo "$(cat log.txt)" >> $GITHUB_STEP_SUMMARY
