name: DITA Workflow

on:
  push:
    branches:
      - dita

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the dita branch
        uses: actions/checkout@v2
        with:
          ref: dita

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install beautifulsoup4

      - name: Run Python script to modify files in the 'out' folder
        run: |
          source venv/bin/activate
          python python/modify_files.py

      - name: Archive the 'out' folder
        run: |
          tar -czf out.tar.gz out

      - name: Check out the dev branch
        uses: actions/checkout@v2
        with:
          ref: dev

      - name: Extract the 'out' folder
        run: |
          tar -xzf out.tar.gz

      - name: Create public folder if it doesn't exist
        run: |
          mkdir -p public

      - name: Copy most files (excluding *.css) from 'out' to 'public'
        run: |
          find out -type f ! -name '*.css' -exec cp --parents \{\} public/ \;

      - name: Commit and push changes to dev branch
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add public/
          git commit -m "Copy files from 'out' to 'public' excluding *.css"
          git push origin dev

      - name: Clean up tar file
        run: |
          rm -f out.tar.gz
