# Used Github Copilot to refactor the workflow from loosely coupled workflows
# to putting the workflow in one file.  

name: DITA Workflow

on:
  push:
    branches:
      - dita

jobs:
  build-html-step:
    uses: ./.github/workflows/build-html.yml
  
  prep-html5-step:
    needs: build-html-step
    uses: ./.github/workflows/prep-html5.yml

#  sitemap-generation-step:
#    needs: prep-html5-step
#    uses: ./.github/workflows/sitemap-generation.yml

#  deploy-dev-to-stage-step:
#    needs: sitemap-generation-step
#    uses: ./.github/workflows/deploy-to-staging.yml

      
