name: Build DITA files
'on':
  push:
    branches:
      - dita

jobs:
  build-dita:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Delete out folder
        run: |
          echo "Deleting out folder"
          rm -rf out

      - name: Build HTML5 
        uses: dita-ot/dita-ot-action@master
        with:
          build: |
            dita --input=dita/orange-heart.ditamap --format=html5 --verbose  --propertyfile=dita/html5.properties 2>&1 | tee log.txt

      - name: Upload log file as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: DITA OT log
          path: log.txt
                  
      - name: List build output
        run: ls -R out
        
      - name: Fetch User Email
        run: |
          EMAIL=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/users/${{ github.actor }}/emails | jq -r '.[0].email')

      - name: Configure git
        run: |
          git config --global user.email "$EMAIL"
          git config --global user.name "${{ github.actor }}"

      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git add out
          if git diff-index --quiet HEAD; then
            echo "No changes to commit"
          else
            git commit -m "Build DITA files"
            git push https://${{ secrets.GH_TOKEN }}@github.com/yetessam/orange-heart-image-addressing.git dita
          fi

      - name: Summarize build
        run: |
          echo "### Summary " >> $GITHUB_STEP_SUMMARY
          echo "$(cat log.txt)" >> $GITHUB_STEP_SUMMARY
