name: Build DITA files

'on':
  push:
    branches:
      - dita

jobs:
  build-dita:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Delete out folder
        run: |
          echo "Deleting out folder"
          rm -rf out

      - name: Build HTML5 
        uses: dita-ot/dita-ot-action@master
        with:
          input: dita/orange-heart.ditamap
          transtype: html5
          output-path: out
          properties: dita/html5-args.properties

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dita-artifact
          path: 'out' # The folder the action should upload.
          
      - name: List build output
        run: ls -R out

      - name: Configure git
        run: |
          git config --global user.email "yasisay@gmail.com"
          git config --global user.name "Yas Etessam"

      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git add out
          if git diff-index --quiet HEAD; then
            echo "No changes to commit"
          else
            git commit -m "Build DITA files"
            git push https://${{ secrets.GH_TOKEN }}@github.com/yetessam/orange-heart-image-addressing.git dita
          fi