name: Build DITA files

'on':
  push:
    branches:
      - content

jobs:
  build-dita:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Delete out folder
        run: |
          echo "Deleting out folder"
          rm -rf out

      - name: Build HTML5 
        uses: dita-ot/dita-ot-action@master
        with:
          input: dita/orange-heart.ditamap
          transtype: html5
          output-path: out

      - name: Configure git
        run: |
          git config --global user.email "yasisay@gmail.com"
          git config --global user.name "Yas Etessam"

      - name: Commit and push changes
        run: |
          git add out
          git commit -m "Build DITA files"
          git push https://${{ secrets.GH_TOKEN }}@github.com/yetessam/orange-heart-image-addressing.git dita
