name: Update XML from Dita Branch

on:
  workflow_dispatch:  # This will allow manual dispatch of the workflow
  workflow_call: 
 # push:
 #   branches: [ stage ]


  
jobs:
  deploy-xml-to-stage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout DITA Branch
        uses: actions/checkout@v3
        with:
          ref: dita

      - name: Copy src Folder to Temporary Location
        run: cp -r content /tmp/content

      - name: Checkout Stage Branch
        run: |
          git fetch origin
          git checkout stage
          git pull origin stage

      - name: Remove Existing xml Folder
        run: rm -rf xml

      - name: Move src Folder from Temporary Location
        run: mv /tmp/content ./xml
 
      - name: Commit and Push changes to Prod
        run: |
            git add xml
            git add -u  # To stage the removal of the old xml folder
            git commit -m "Clobber existing xml folder with content from dita branch"
            git push origin prod

