# This workflow file was originally sourced from:
# https://github.com/cicirello/actions/blob/main/.github/workflows/sitemap-generation.yml
# Modified by [Yas Etessam] for [orange-heart-project]

name: Generate sitemap

on:
  workflow_dispatch:

jobs:
  sitemap:
    name: Generating site map 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout dev Branch
      run: |
          git fetch origin
          git checkout dev
          git pull origin dev

    - name: Checkout the repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0    # Need timestamp info
    
    - name: Generate the sitemap
      id: sitemap
      uses: cicirello/generate-sitemap@v1
      with:
        base-url-path: https://delicate-glitter-6121.on-fleek.app
    
    - name: Output stats
      run: |
        cp ${{ steps.sitemap.outputs.sitemap-path }} src/sitemap.xml
        echo "sitemap-path = ${{ steps.sitemap.outputs.sitemap-path }}"
        echo "url-count = ${{ steps.sitemap.outputs.url-count }}"
        echo "excluded-count = ${{ steps.sitemap.outputs.excluded-count }}"
    
    - name: Commit and push
      run: |
        if [[ `git status --porcelain src/sitemap.xml` ]]; then
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add src/sitemap.xml
          git commit -m "Automated sitemap update" src/sitemap.xml
          git push
        fi
